In [7]:
import pytesseract
import cv2
import re

In [8]:
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

In [9]:
pytesseract.image_to_string("ocrimage.jpeg")

'It was the best of\ntimes, it was the worst\nof times, it was the age\nof wisdom, it was the\nage of foolishness...\n'

In [4]:
img_array=cv2.imread("ocrimage.jpeg")
dict1=pytesseract.image_to_data(img_array,output_type=pytesseract.Output.DICT)

In [5]:
pytesseract.image_to_data(img_array,output_type=pytesseract.Output.DATAFRAME)

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,282,178,-1.000000,NaN
1,2,1,1,0,0,0,8,9,268,162,-1.000000,NaN
2,3,1,1,1,0,0,8,9,268,162,-1.000000,NaN
3,4,1,1,1,1,0,8,9,206,21,-1.000000,NaN
4,5,1,1,1,1,1,8,10,19,20,92.522881,It
5,5,1,1,1,1,2,35,17,42,13,96.953987,was
6,5,1,1,1,1,3,86,10,37,20,97.005020,the
7,5,1,1,1,1,4,132,9,47,21,97.012764,best
8,5,1,1,1,1,5,188,9,26,21,96.998497,of
9,4,1,1,1,2,0,8,43,263,25,-1.000000,NaN
10,5,1,1,1,2,1,8,44,69,24,96.359825,"times,"
11,5,1,1,1,2,2,86,44,17,19,96.745949,it
12,5,1,1,1,2,3,110,51,43,13,96.558609,was
13,5,1,1,1,2,4,162,43,36,20,96.553177,the
14,5,1,1,1,2,5,206,48,65,16,96.589928,worst
15,4,1,1,1,3,0,8,76,268,28,-1.000000,NaN
16,5,1,1,1,3,1,8,76,26,21,96.138939,of
17,5,1,1,1,3,2,39,78,70,23,96.138939,"times,"
18,5,1,1,1,3,3,118,78,17,19,96.232605,it
19,5,1,1,1,3,4,142,84,42,13,96.232605,was
20,5,1,1,1,3,5,193,76,37,21,97.004959,the
21,5,1,1,1,3,6,239,84,37,20,96.965958,age
22,4,1,1,1,4,0,8,110,248,25,-1.000000,NaN
23,5,1,1,1,4,1,8,110,22,21,96.952995,of
24,5,1,1,1,4,2,38,110,97,25,96.914169,"wisdom,"
25,5,1,1,1,4,3,144,112,17,18,96.903816,it
26,5,1,1,1,4,4,168,118,42,13,96.362320,was
27,5,1,1,1,4,5,219,110,37,21,96.946037,the
28,4,1,1,1,5,0,8,143,225,28,-1.000000,NaN
29,5,1,1,1,5,1,8,151,37,20,96.873344,age
30,5,1,1,1,5,2,54,143,26,21,96.968048,of
31,5,1,1,1,5,3,86,143,147,21,95.863937,foolishness...

In [17]:
x1=8
y1=44	
x2=8+69	
y2=44+24	
cv2.rectangle(img_array,(x1,y1),(x2,y2),(0,25,255),2)
cv2.imshow("ocr",img_array)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

In [ ]:
img_array=cv2.imread("ocrimage.jpeg")
dict1=pytesseract.image_to_data(img_array,output_type=pytesseract.Output.DICT)
for i in range(len(dict1["text"])):
    if dict1["conf"][i]>30:
        if len(dict1["text"][i])>4:
            x,y,w,h=dict1["left"][i],dict1["top"][i],dict1["width"][i],dict1["height"][i]
            cv2.rectangle(img_array,(x,y),(x+w,y+h),(0,25,255),2)
cv2.imshow("ocr",img_array)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

In [ ]:
dict1[""]

KeyError: ''

REGULAR EXPRESISION

In [ ]:
def match_patterns(img_array,pattern,number):
    email=[]
    phno=[]
    dict1=pytesseract.image_to_data(img_array,output_type=pytesseract.Output.DICT)
    for i in range(len(dict1["left"])):
        if dict1["conf"][i]>30:
            text=dict1["text"][i]            
            if re.match(pattern,text) :
                email.append(text)
                x,y,w,h=dict1["left"][i],dict1["top"][i],dict1["width"][i],dict1["height"][i]
                cv2.rectangle(img_array,(x,y),(x+w,y+h),(0,25,255),2)
        if dict1["text"][i].isnumeric(): 
            num=dict1["text"][i]
            if re.fullmatch(number,num) :
                phno.append(num)
                x,y,w,h=dict1["left"][i],dict1["top"][i],dict1["width"][i],dict1["height"][i]
                cv2.rectangle(img_array,(x,y),(x+w,y+h),(0,25,255),2)

    cv2.imshow("ocr",img_array)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return email,phno

In [ ]:
text=cv2.imread("idcard.jpeg")
pattern=r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.com"
number=r"\+\d{3}-\d{3}-\d{4}"
match_patterns(text,pattern,number)

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

In [ ]:
from PIL import Image
import streamlit as st
import pytesseract
pytesseract.pytesseract.tesseract_cmd=r"C:\Program Files\Tesseract-OCR\tesseract.exe"
import re
import cv2
def match_patterns(img_arr,pattern):
    # img_arr=cv2.resize(img_arr,(400,400))
    import re
    emails=[]
    dict1=pytesseract.image_to_data(img_arr,output_type=pytesseract.Output.DICT)
    for i in range(len(dict1['top'])):
        if dict1['conf'][i]>30:
            text=dict1['text'][i]
            if re.match(pattern,text):
                emails.append(text)
                
    
    return emails
email=re.compile(r"\b[a-zA-Z0-9]+@[a-zA-Z0-9.]+\.com\b")
mobile=re.compile(r"\+?9?1?\d{10}\b")
st.title('Email Extractor From Image')
file=st.file_uploader('Upload image',type=['jpg','jpeg','png'])
patter=st.selectbox("Select pattern",['Email',"Mobile number(IND)"])


button=st.button('Extract')
if button and patter=='Email' and file:
    image=Image.open(file)
    data=match_patterns(image,email)
    if data:
        for i in data:
            st.write(f"{i}\n")
    else:
        st.write("No data")